/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.view;

import com.bank.model.AccountDAO;
import com.bank.model.AccountDTO;
import com.bank.model.BankUserDAO;
import com.bank.model.BankUserDTO;
import com.bank.model.BankUserService;
import com.bank.model.DealDAO;
import com.bank.model.DealDTO;
import com.bank.thread.LoginActiveThread;
import com.bank.thread.MyRenderer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ad
 */
public class BankMain extends javax.swing.JFrame implements ActionListener, KeyListener, MouseListener,ItemListener{
    BankUserDTO dto;
    BankUserDAO dao;
    BankUserDTO userdto;
    AccountDTO acdto;
    AccountDAO acdao;
    DealDAO dealdao;
    DealDTO dealdto;
    List<AccountDTO> listac;
    DecimalFormat df;
    String loginid = BankUserService.getUserid();
    String nowview ="";
    LoginActiveThread lat;
    /**
     * Creates new form bankMain
     */
    public BankMain() {
        super("은행");
        initComponents();
        init();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tpmain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tpviewac = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lapricesum = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lausername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pactable = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbviewac = new javax.swing.JComboBox<>();
        btviewac = new javax.swing.JButton();
        tfdate1 = new javax.swing.JTextField();
        tfdate2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        checkdate = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbviewac = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfpirce = new javax.swing.JTextField();
        tfacpwd = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbwithdraw = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tfdeposit = new javax.swing.JTextField();
        bttransfer = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbaccounttype = new javax.swing.JComboBox<>();
        tfaccountpwd = new javax.swing.JPasswordField();
        tfaccountpwdc = new javax.swing.JPasswordField();
        btaccountopen = new javax.swing.JButton();
        lapwdequals = new javax.swing.JLabel();
        lausername2 = new javax.swing.JLabel();
        laactivetime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btlogout = new javax.swing.JButton();
        btmembermodify = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpmain.setToolTipText("");

        tpviewac.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tpviewac.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("총 잔액"));

        jLabel5.setText("원");

        lapricesum.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 135, Short.MAX_VALUE)
                .addComponent(lapricesum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lapricesum))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lausername.setText("고객님");

        jLabel2.setText("환영합니다!");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lausername))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lausername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pactable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pactable.setMinimumSize(new java.awt.Dimension(722, 239));

        javax.swing.GroupLayout pactableLayout = new javax.swing.GroupLayout(pactable);
        pactable.setLayout(pactableLayout);
        pactableLayout.setHorizontalGroup(
            pactableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        pactableLayout.setVerticalGroup(
            pactableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pactable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pactable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpviewac.addTab("계좌조회", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        tpviewac.addTab("거래내역 조회", jPanel5);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("간편조회"));

        jLabel6.setText("계좌번호");

        jLabel7.setText("날짜");

        btviewac.setText("조회");

        jLabel10.setText("~");

        checkdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbviewac, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(tfdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(btviewac)
                .addGap(68, 68, 68))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbviewac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(tfdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(checkdate)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btviewac)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbviewac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "상대방 이름", "상대방 계좌", "금액", "날짜"
            }
        ));
        tbviewac.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbviewac);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpviewac.addTab("간편 조회", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tpviewac)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tpviewac)
                .addContainerGap())
        );

        tpmain.addTab("조회", jPanel1);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("출금계좌정보"));

        jLabel9.setText("출금계좌번호");

        jLabel12.setText("출금계좌비밀번호");

        jLabel13.setText("이체금액");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfacpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpirce, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(cbwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfacpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfpirce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("입금계좌정보"));

        jLabel15.setText("입금계좌번호");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(tfdeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        bttransfer.setText("이체");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttransfer)
                .addGap(404, 404, 404))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttransfer)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        tpmain.addTab("이체", jPanel2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        tpmain.addTab("금융상품", jPanel9);

        jLabel1.setText("계좌 종류");

        jLabel3.setText("계좌 비밀번호");

        jLabel4.setText("비밀번호 확인");

        cbaccounttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "일반계좌", "신용계좌", "적금계좌" }));

        btaccountopen.setText("개설");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfaccountpwd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbaccounttype, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfaccountpwdc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lapwdequals))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(btaccountopen)))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbaccounttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfaccountpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfaccountpwdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lapwdequals))
                .addGap(106, 106, 106)
                .addComponent(btaccountopen)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        tpmain.addTab("계좌개설", jPanel3);

        lausername2.setText("이름");

        laactivetime.setForeground(new java.awt.Color(255, 51, 0));
        laactivetime.setText("03:00");

        jLabel8.setText("후 자동 로그아웃 됩니다.");

        btlogout.setText("로그아웃");

        btmembermodify.setText("회원 정보 수정");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpmain)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lausername2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laactivetime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btmembermodify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlogout)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lausername2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laactivetime)
                    .addComponent(jLabel8)
                    .addComponent(btmembermodify)
                    .addComponent(btlogout))
                .addGap(29, 29, 29)
                .addComponent(tpmain, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaccountopen;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btmembermodify;
    private javax.swing.JButton bttransfer;
    private javax.swing.JButton btviewac;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbaccounttype;
    private javax.swing.JComboBox<String> cbviewac;
    private javax.swing.JComboBox<String> cbwithdraw;
    private javax.swing.JCheckBox checkdate;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel laactivetime;
    private javax.swing.JLabel lapricesum;
    private javax.swing.JLabel lapwdequals;
    private javax.swing.JLabel lausername;
    private javax.swing.JLabel lausername2;
    private javax.swing.JPanel pactable;
    private javax.swing.JTable tbviewac;
    private javax.swing.JPasswordField tfaccountpwd;
    private javax.swing.JPasswordField tfaccountpwdc;
    private javax.swing.JPasswordField tfacpwd;
    private javax.swing.JTextField tfdate1;
    private javax.swing.JTextField tfdate2;
    private javax.swing.JTextField tfdeposit;
    private javax.swing.JTextField tfpirce;
    private javax.swing.JTabbedPane tpmain;
    private javax.swing.JTabbedPane tpviewac;
    // End of variables declaration//GEN-END:variables


    private void init() {
        dto = new BankUserDTO();
        dao = new BankUserDAO();
        acdao = new AccountDAO();
        acdto = new AccountDTO();
        dealdto = new DealDTO();
        dealdao = new DealDAO();
        listac = new ArrayList<>();
        df = new DecimalFormat("###,###");
        
        listacinit();
        lat = new LoginActiveThread(laactivetime,this);
        lat.start();
        
        lausername.setText(userdto.getName()+" 고객님");
        lausername2.setText(userdto.getName()+"님 ");
        tfdate1.setEnabled(false);
        tfdate2.setEnabled(false);
        
        BankUserService.setUseremail(userdto.getEmail());
        BankUserService.setUserjoindate(userdto.getJoindate());
        BankUserService.setUserjumin(userdto.getJumin());
        BankUserService.setUsername(userdto.getName());
        BankUserService.setUserno(userdto.getSeq());
        BankUserService.setUserpwd(userdto.getPwd());
        BankUserService.setUsertel(userdto.getTel());
        
        
    }
    
    private void addEvent() {
        //계좌 개설
        btaccountopen.addActionListener(this);
        tfaccountpwd.addKeyListener(this);
        tfaccountpwdc.addKeyListener(this);
        
        //전체 계좌 조회
        tpmain.addMouseListener(this);
        
        //계좌 이체
        bttransfer.addActionListener(this);
        tfacpwd.addKeyListener(this);
        tfpirce.addKeyListener(this);
        tfdeposit.addKeyListener(this);
        
        //계좌별 조회
        tpviewac.addMouseListener(this);
        btviewac.addActionListener(this);
        tfdate1.addKeyListener(this);
        tfdate2.addKeyListener(this);
        checkdate.addItemListener(this);
        //로그아웃
        btlogout.addActionListener(this);
        
        //회원정보수정
        btmembermodify.addActionListener(this);
        
        
    }

    
    @Override
    public void actionPerformed(ActionEvent e) {
        LoginActiveThread.setTime(180);
        try {
            if(e.getSource()==btaccountopen){//계좌 개설 버튼 이벤트
                openAccount();
            }
            
            else if(e.getSource()==bttransfer){//계좌 이체 버튼 이벤트
                actransfer();
            }
            
            else if(e.getSource()==btviewac){//계좌별 조회 버튼 이벤트
                acview();
            }
            
            else if(e.getSource()==btlogout){
                logout();
            }
            
            else if (e.getSource()==btmembermodify){
                membermodify();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(BankMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
//--------------------------------------------------------------------KeyListener---------------------------------------------------------------------------------
    @Override
    public void keyTyped(KeyEvent e) {
        LoginActiveThread.setTime(180);
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if(e.getSource()==tfaccountpwd){//계좌 개설
            Join j = new Join();
            String s = tfaccountpwd.getText();
            if(!(j.digitcheck(s))){
                tfaccountpwd.setText("");
            }
            else if(s.length()>4){
                s=s.substring(0,4);
                tfaccountpwd.setText(s);
            }
                
        }else if(e.getSource()==tfaccountpwdc){//계좌 개설
            String p1= tfaccountpwd.getText();
            String p2= tfaccountpwdc.getText();
            Join j = new Join();
            
            if(!(j.digitcheck(p2))){
                tfaccountpwdc.setText("");
            }
            else if(p2.length()>4){
                p2=p2.substring(0,4);
                tfaccountpwdc.setText(p2);
            }
            
            if(p1.equals(p2)){
                lapwdequals.setText("비밀번호 일치");
            }else
                lapwdequals.setText("비밀번호 불일치");
        
        }else if(e.getSource()==tfacpwd){// 계좌 이체
            Join j = new Join();
            String s = tfacpwd.getText();
            if(!(j.digitcheck(s))){
                tfacpwd.setText("");
            }
            else if(s.length()>4){
                s=s.substring(0,4);
                tfacpwd.setText(s);
            }
        
        }else if(e.getSource()==tfpirce){// 계좌 이체
            Join j = new Join();
            String s = tfpirce.getText();
            if(!(j.digitcheck(s))){
                tfpirce.setText("");
            }
       
        }else if(e.getSource()==tfdeposit){// 계좌 이체
            Join j = new Join();
            String s = tfdeposit.getText();
            if(!(j.digitcheck(s))){
                tfdeposit.setText("");
            }
            else if(s.length()>13){
                s=s.substring(0,13);
                tfdeposit.setText(s);
            }
        }
        else if(e.getSource()==tfdate1){// 계좌 조회
            Join j = new Join();
            String s = tfdate1.getText();
            if(!(j.digitcheck(s))){
                tfdate1.setText("");
            }
            else if(s.length()>8){
                s=s.substring(0,8);
                tfdate1.setText(s);
            }
        }else if(e.getSource()==tfdate2){// 계좌 조회
            Join j = new Join();
            String s = tfdate2.getText();
            if(!(j.digitcheck(s))){
                tfdate2.setText("");
            }
            else if(s.length()>8){
                s=s.substring(0,8);
                tfdate2.setText(s);
            }
        }
        
    }
//----------------------------------------------------------------------------------------------------------------------------------------------------------
    
    //계좌 개설
    private void openAccount() throws SQLException {
        int actype = (int)cbaccounttype.getSelectedIndex()+1;
        String pwd = tfaccountpwd.getText();
        String pwdc = tfaccountpwdc.getText();
        int cnt=acdao.userAcCnt(userdto.getSeq());
        
        if(cnt>=6){
             JOptionPane.showMessageDialog(this, "더 이상 개설이 불가능합니다.","계좌 개설",JOptionPane.INFORMATION_MESSAGE);
             return;
        }
         
        if(pwd==null || pwd.isEmpty() || pwd.length()!=4){
            JOptionPane.showMessageDialog(this, "비밀번호를 확인하세요","계좌 개설",JOptionPane.INFORMATION_MESSAGE);
            tfaccountpwd.requestFocus();
            return;
        }
        if(pwdc==null || pwdc.isEmpty() || !(pwdc.equals(pwd))){
            JOptionPane.showMessageDialog(this, "비밀번호를 확인하세요","계좌 개설",JOptionPane.INFORMATION_MESSAGE);
            tfaccountpwdc.requestFocus();
            return;
        }
        
        acdto.setAcpwd(Integer.parseInt(pwd));
        acdto.setTypeno(actype);
        acdto.setUserno(userdto.getSeq());
        
        int j = acdao.insertAccount(acdto);
            
        if(j>0){
            JOptionPane.showMessageDialog(this, "개설완료","계좌 개설",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }
    
    //전체 계좌 조회
    private void showlistac(int accnt) {
        pactable.setLayout(new GridLayout(accnt,1));
        JPanel[] plistac = new JPanel[accnt];
        JButton[] btlistac = new JButton[accnt];
        JLabel[] lalistac = new JLabel[accnt];
        
        for(int i=0; i<plistac.length; i++){
            plistac[i]=new JPanel();    
            AccountDTO lacdto= new AccountDTO();
            lacdto=listac.get(i);
            String acnum = Long.toString(lacdto.getAccountno());
            String acprice = df.format(lacdto.getPrice());
            
            lalistac[i]=new JLabel(" 계좌 : "+acnum);
            lalistac[i].setPreferredSize(new Dimension(200,18));
            plistac[i].add(lalistac[i]);
            
            lalistac[i]=new JLabel("잔액 : "+acprice+"원",JLabel.RIGHT);
            lalistac[i].setPreferredSize(new Dimension(464,18));
            plistac[i].add(lalistac[i]);
            
            btlistac[i]=new JButton("조회");
            btlistac[i].addActionListener(new ActionListener(){
               
                @Override
                public void actionPerformed(ActionEvent e) {
                    acviewinit();
                    cbviewac.setSelectedItem(acnum);
                    try {
                        acview();
                    } catch (SQLException ex) {
                        Logger.getLogger(BankMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    tpviewac.setSelectedIndex(2);
                }
                    
            });
            plistac[i].add(btlistac[i]);
            
            pactable.add(plistac[i]);
            
        }
        
    }

    //전체 계좌 조회 화면
    private void listacinit() {
        pactable.removeAll();
        try {
            userdto= dao.loginUser(loginid);
            listac = acdao.userAcList(userdto.getSeq());
        } catch (SQLException ex) {
            Logger.getLogger(BankMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(listac.isEmpty() || listac==null){
            pactable.setLayout(new BorderLayout());
            JLabel jl = new JLabel("계좌가 없습니다.",JLabel.CENTER);
            jl.setPreferredSize(new Dimension(735,20));
            pactable.add(jl);
            
           
            
        }else{
            long sum =0;
            for(AccountDTO n : listac){
                sum+= n.getPrice();
            }
            String sumprice = df.format(sum);
            lapricesum.setText(sumprice);
            showlistac(listac.size());
        }
    }
    
    //계좌 이체 화면
    private void tansferinit() {
        try {
            listac = acdao.userAcList(userdto.getSeq());
        } catch (SQLException ex) {
            Logger.getLogger(BankMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(listac.isEmpty() || listac==null){
            DefaultComboBoxModel<String> cModel=new DefaultComboBoxModel<>();
            cModel.addElement("-----계좌가 없습니다-----");
            cbwithdraw.setModel(cModel);
        }else{
            Vector<String> vec = new Vector<>();
            for(int i=0; i<listac.size(); i++){
                vec.add(Long.toString(listac.get(i).getAccountno()));
            }
            DefaultComboBoxModel<String> cModel=new DefaultComboBoxModel<>(vec);
            cbwithdraw.setModel(cModel);
        }
    }
    
    //계좌 이체
    private void actransfer() throws SQLException {
        String pwd = tfacpwd.getText();
        String price = tfpirce.getText();
        String withdraw = (String)cbwithdraw.getSelectedItem();
        String deposit = tfdeposit.getText();
        
        
        if(pwd==null || pwd.isEmpty() || pwd.length()!=4){
            JOptionPane.showMessageDialog(this, "비밀번호를 확인하세요","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            tfaccountpwd.requestFocus();
            return;
        }
        if(price==null || price.isEmpty() || Long.parseLong(price)<=0 ){
            JOptionPane.showMessageDialog(this, "금액을 확인하세요","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            tfaccountpwd.requestFocus();
            return;
        }
        if(deposit==null || deposit.isEmpty() || deposit.length()!=13){
            JOptionPane.showMessageDialog(this, "받는분의 계좌번호를 확인하세요","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            tfaccountpwd.requestFocus();
            return;
        }
        if(withdraw.equals("-----계좌가 없습니다-----")){
            JOptionPane.showMessageDialog(this, "선택한 계좌가 없습니다.","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(withdraw.equals(deposit)){
            JOptionPane.showMessageDialog(this, "동일한 계좌번호입니다.","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        long pri= Long.parseLong(price);
        AccountDTO withdrawac = new AccountDTO();
        withdrawac= acdao.acInfo(withdraw);
        
        if(withdrawac.getAcpwd()!=Integer.parseInt(pwd)){
            JOptionPane.showMessageDialog(this, "비밀번호가 올바르지 않습니다.","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(withdrawac.getPrice()<pri){
            JOptionPane.showMessageDialog(this, "계좌에 보유한 금액이 부족합니다.","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        AccountDTO depositac = new AccountDTO();
        depositac = acdao.acInfo(deposit);
        
        if(depositac==null){
            JOptionPane.showMessageDialog(this, "받는분의 계좌번호가 없습니다.","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
            return;
        }else{
            String dname= dao.selectNameByNo(depositac.getUserno());
            int transType=JOptionPane.showConfirmDialog(this, "받는분 : "+dname+"\n계좌번호 : "+depositac.getAccountno()+"\n이체하시겠습니까?","이체",
                JOptionPane.YES_NO_OPTION);
            
            if(transType==JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(this, "취소하였습니다.");
                return;
            }
        }
        
        DealDTO dealdto= new DealDTO();
        dealdto.setSendac(withdrawac.getAccountno());
        dealdto.setSendprice(pri);
        dealdto.setSenduser(dao.selectNameByNo(withdrawac.getUserno()));
        dealdto.setTakeac(depositac.getAccountno());
        dealdto.setTakeprice(pri);
        dealdto.setTakeuser(dao.selectNameByNo(depositac.getUserno()));
        
        
       int dealcheck = dealdao.insertDeal(dealdto);
       int sendcheck = acdao.sendPrice(withdrawac.getAccountno(), pri);
       int takecheck = acdao.takePrice(depositac.getAccountno(), pri);
       
       if(dealcheck>0 || sendcheck>0 || takecheck>0){
           JOptionPane.showMessageDialog(this, "이체 완료","계좌 이체",JOptionPane.INFORMATION_MESSAGE);
       }
    }
    
    //계좌별 조회 화면
    private void acviewinit() {
        try {
            listac = acdao.userAcList(userdto.getSeq());
        } catch (SQLException ex) {
            Logger.getLogger(BankMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(listac.isEmpty() || listac==null){
            DefaultComboBoxModel<String> cModel=new DefaultComboBoxModel<>();
            cModel.addElement("-----계좌가 없습니다-----");
            cbviewac.setModel(cModel);
        }else{
            Vector<String> vec = new Vector<>();
            for(int i=0; i<listac.size(); i++){
                vec.add(Long.toString(listac.get(i).getAccountno()));
            }
            DefaultComboBoxModel<String> cModel=new DefaultComboBoxModel<>(vec);
            cbviewac.setModel(cModel);
        }
    }
    
    //계좌별 조회
    private void acview() throws SQLException { 
        String dealac = (String)cbviewac.getSelectedItem();
        List<DealDTO> listdto;
        
        
         if(!checkdate.isSelected()){
            listdto= dealdao.selectDealByAc(dealac);
         }else{
            String date2 = tfdate2.getText();
            String date1 = tfdate1.getText();
      
            if(date1.length()<8 || date2.length()<8 || !datecheck(date1) || !datecheck(date2) || Long.parseLong(date1)>Long.parseLong(date2)){
                JOptionPane.showMessageDialog(this, "잘못된 날짜 형식입니다.","계좌 조회",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            listdto=dealdao.selectDealByAcDate(dealac, date1, date2);
         }
        
        String[] colNames={"상대방 이름","상대방 계좌","금액","날짜"};
        Object[][] data = new Object[listdto.size()][colNames.length];
        System.out.println(listdto.size());
        
       
            
        
        
        for(int i=0; i<listdto.size(); i++){
            DealDTO ddto= listdto.get(i);
            if(ddto.getSendac()==Long.parseLong(dealac)){
                data[i][0]= ddto.getTakeuser();
                data[i][1]= ddto.getTakeac();
                data[i][2]= -ddto.getSendprice();
                data[i][3]= ddto.getDealdate();
            }else{
                
                data[i][0]= ddto.getSenduser();
                data[i][1]= ddto.getSendac();
                data[i][2]= ddto.getSendprice();
                data[i][3]= ddto.getDealdate();
                
            }
            
        }
        DefaultTableModel model = new DefaultTableModel();
        model.setDataVector(data, colNames);  
        tbviewac.setModel(model);
        
        tbviewac.getColumnModel().getColumn(0).setPreferredWidth(20);
        tbviewac.getColumnModel().getColumn(1).setPreferredWidth(30);
        tbviewac.getColumnModel().getColumn(2).setPreferredWidth(170);
        tbviewac.getColumnModel().getColumn(3).setPreferredWidth(60);
        
        
        DefaultTableCellRenderer ren = new MyRenderer();
        ren.setHorizontalAlignment(SwingConstants.RIGHT);
        tbviewac.getColumnModel().getColumn(2).setCellRenderer(ren);
        
//        try {
//            tbviewac.setDefaultRenderer(Class.forName("java.lang.Object"), ren);
//            
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(BankMain.class.getName()).log(Level.SEVERE, null, ex);
//        }    
//        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
//        dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
//        tbviewac.getColumnModel().getColumn(2).setCellRenderer(dtcr);
    }
    
    //클리어
    public void cleartpmain1(){
        tfacpwd.setText("");
        tfpirce.setText("");
        tfdeposit.setText("");
        cbwithdraw.setSelectedIndex(0);
    }
 
    //클리어
    public void cleartpmain3(){
        tfaccountpwd.setText("");
        tfaccountpwdc.setText("");
        cbaccounttype.setSelectedIndex(0);
    }
 
    //클리어
    public void cleartbviewac2(){
        DefaultTableModel model = new DefaultTableModel();  
        cbviewac.setSelectedItem(0);
    }
    
    //로그아웃
    private void logout() {
        Login login = new Login();
        lat.stop();
        this.dispose();
        login.setVisible(true);
    }
    
    //정보수정
    private void membermodify() {
        Join join = new Join(2);
        join.setVisible(true);
        
    }
//--------------------------------------------------------------------mouseListener---------------------------------------------------------------------------------
    @Override
    public void mouseClicked(MouseEvent e) {
        LoginActiveThread.setTime(180);
        if(e.getSource()==tpmain){
                int index =((JTabbedPane)e.getSource()).getSelectedIndex();
                if(index==0 && !nowview.equals("tpmain0")){
                    listacinit();
                    nowview="tpmain0";
                }else if(index==1 && !nowview.equals("tpmain1")){
                    tansferinit();
                    nowview="tpmain1";
                    cleartpmain1();
                }else if(index==2 && !nowview.equals("tpmain2")){                   
                    nowview="tpmain2";
                }else if(index==3 && !nowview.equals("tpmain3")){                   
                    nowview="tpmain3";
                    cleartpmain3();
                }
        }else if(e.getSource()==tpviewac ){
                int index =((JTabbedPane)e.getSource()).getSelectedIndex();
                if(index==0 && !nowview.equals("tpviewac0")){
                    listacinit();
                    nowview="tpviewac0";
                }else if(index==2 && !nowview.equals("tpviewac2")){
                    acviewinit();
                    nowview="tpviewac2";
                    cleartbviewac2();
                }
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
//----------------------------------------------------------------------------itemListener-------------------------------------------------------------------------------------    
    @Override
    public void itemStateChanged(ItemEvent e) {
        if(e.getSource()==checkdate){
            if(e.getStateChange()==ItemEvent.SELECTED){
                tfdate1.setEnabled(true);
                tfdate2.setEnabled(true);
            }else{
                tfdate1.setEnabled(false);
                tfdate2.setEnabled(false);
            }
        }
    }
//--------------------------------------------------------------------------------------------------------------------------------------------------------------------

    public boolean datecheck(String date){
        boolean bool = true;
        int year = Integer.parseInt(date.substring(0,4));
        int month = Integer.parseInt(date.substring(4,6));
        int day = Integer.parseInt(date.substring(6,8));
        
        if(month>12 || month<1 || day>31 || day<1)
            return false;
        
        switch(month){
            case 4:
            case 6:
            case 9:
            case 11:
                if(day>30)
                    bool = false;
                break;
            case 2:
                if((year % 4 == 0 && year % 100 != 0) || year % 400 == 0 ){
                    if(day>29)
                        bool = false;
                }
                else{
                    if(day>28)
                        bool = false;
                }
                break;
        }
        return bool;
    }

    
}
