/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.view;

import com.bank.model.BankUserDAO;
import com.bank.model.BankUserDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author knit
 */
public class IdPwdSearch extends javax.swing.JFrame implements ActionListener,KeyListener {
    BankUserDTO dto;
    BankUserDAO dao;
    
    /**
     * Creates new form IdPwdSearch
     */
 
    public IdPwdSearch() {
        super("ID/PWD 찾기");
        initComponents();
        init();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        laname = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfjumin1 = new javax.swing.JTextField();
        lajumin = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        tfjumin2 = new javax.swing.JPasswordField();
        btsearch = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laname.setText("이름");

        lajumin.setText("주민번호");

        s.setText("-");

        btsearch.setText("찾기");

        btcancel.setText("취소");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laname)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lajumin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btsearch)
                                .addGap(18, 18, 18)
                                .addComponent(btcancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfname, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(tfjumin1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfjumin2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laname)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lajumin)
                    .addComponent(tfjumin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s)
                    .addComponent(tfjumin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsearch)
                    .addComponent(btcancel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdPwdSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdPwdSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdPwdSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdPwdSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdPwdSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancel;
    private javax.swing.JButton btsearch;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lajumin;
    private javax.swing.JLabel laname;
    private javax.swing.JLabel s;
    private javax.swing.JTextField tfjumin1;
    private javax.swing.JPasswordField tfjumin2;
    private javax.swing.JTextField tfname;
    // End of variables declaration//GEN-END:variables

    private void init() {
        dto = new BankUserDTO();
        dao = new BankUserDAO();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void addEvent() {
        btsearch.addActionListener(this);
        btcancel.addActionListener(this);
        tfjumin1.addKeyListener(this);
        tfjumin2.addKeyListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btsearch){
            try {
                searchIdPwd();
            } catch (SQLException ex) {
                Logger.getLogger(IdPwdSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(e.getSource()==btcancel){
            this.dispose();
        }
    }

    private void searchIdPwd() throws SQLException {
        String name = tfname.getText();
        String jumin1 = tfjumin1.getText();
        String jumin2 = tfjumin2.getText();
        String jumin="";
        
        if(name==null || name.isEmpty()){
            JOptionPane.showMessageDialog(this, "이름을 확인하세요","ID/PWD 찾기",JOptionPane.INFORMATION_MESSAGE);
            tfname.requestFocus();
            return;
        }
        if(jumin1==null || jumin1.isEmpty() || jumin2==null || jumin2.isEmpty()){
            JOptionPane.showMessageDialog(this, "주민번호를 확인하세요","ID/PWD 찾기",JOptionPane.INFORMATION_MESSAGE);
            tfjumin1.requestFocus();
            return;
        }
        jumin=jumin1+jumin2;
        jumincheck(name,jumin);
        
        
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        Join j = new Join();
        if(e.getSource()== tfjumin1){
            String s = tfjumin1.getText();
            if(!(j.digitcheck(s))){
                tfjumin1.setText("");
            }else if(s.length()>6){
                s=s.substring(0,6);
                tfjumin1.setText(s);
            }
            if(tfjumin1.getText().length()==6)
                tfjumin2.requestFocus();
            
        }else if(e.getSource()==tfjumin2){
            String s = tfjumin2.getText();
            if(!(j.digitcheck(s))){
                tfjumin2.setText("");
            }
            else if(s.length()>7){
                s=s.substring(0,7);
                tfjumin2.setText(s);
            }
        }
    }

    private void jumincheck(String name, String jumin) throws SQLException {
        if(dao.namejuminCheck(name,jumin)){
            dto=dao.searchIdPwd(name, jumin);
            String userid= dto.getId();
            String userpwd=dto.getPwd();
            JOptionPane.showMessageDialog(this, "아이디 : "+userid+", 비밀번호 : "+userpwd+" 입니다.","ID/PWD 찾기",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "가입된 정보가 없습니다.","ID/PWD 찾기",JOptionPane.INFORMATION_MESSAGE);
        }
    }

    
}
